version: "3.8"

services:
  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./conf/redis-1.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:latest
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./conf/redis-2.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:6379"
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:latest
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./conf/redis-3.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:6379"
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:latest
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./conf/redis-4.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7004:6379"
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:latest
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./conf/redis-5.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7005:6379"
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:latest
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./conf/redis-6.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7006:6379"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
